artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: https://github.com/entbappy/Branching-tutorial/raw/master/marketing_campaign.zip
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data

data_validation_config:
  clean_data_dir: clean_data
  serialized_objects_dir: serialized_objects
  marketing_campaign_csv_file: marketing_campaign.csv
  

data_transformation_config:
  transformed_data_dir: transformed_data


model_trainer_config:
  trained_model_dir: trained_model
  trained_model_name: model.pkl




